# 台股爬蟲

證交所網站

In [5]:
import requests
from io import StringIO
import pandas as pd
import numpy as np

datestr = '20180131'

# 下載股價
r = requests.post('https://www.twse.com.tw/exchangeReport/MI_INDEX?response=csv&date=' + datestr + '&type=ALL')

# 整理資料，變成表格
df = pd.read_csv(StringIO(r.text.replace("=", "")), 
            header=["證券代號" in l for l in r.text.split("\n")].index(True)-1)

# 整理一些字串：
df = df.apply(lambda s: pd.to_numeric(s.astype(str).str.replace(",", "").replace("+", "1").replace("-", "-1"), errors='coerce'))

# 顯示出來
df.head()

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,Unnamed: 16
0,50.0,NaN,4251739,1176,359040915,84.40,85.00,84.15,84.65,1.0,0.10,84.60,21,84.65,80,0.0,NaN
1,51.0,NaN,7500,3,243040,32.39,32.39,32.39,32.39,1.0,0.09,32.39,43,32.50,5,0.0,NaN
2,52.0,NaN,4001,5,229706,57.35,57.60,57.30,57.40,1.0,0.05,57.35,1,57.90,1,0.0,NaN
3,53.0,NaN,1,1,37,NaN,NaN,NaN,NaN,NaN,0.00,37.09,50,37.35,1,0.0,NaN
4,54.0,NaN,2001,3,48904,24.44,24.44,24.44,24.44,-1.0,0.05,24.41,50,24.64,8,0.0,NaN

In [22]:
df[pd.to_numeric(df['本益比'], errors='coerce') < 15]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,Unnamed: 16
0,50.0,NaN,4251739,1176,359040915,84.40,85.00,84.15,84.65,1.0,0.10,84.60,21,84.65,80,0.00,NaN
1,51.0,NaN,7500,3,243040,32.39,32.39,32.39,32.39,1.0,0.09,32.39,43,32.50,5,0.00,NaN
2,52.0,NaN,4001,5,229706,57.35,57.60,57.30,57.40,1.0,0.05,57.35,1,57.90,1,0.00,NaN
3,53.0,NaN,1,1,37,NaN,NaN,NaN,NaN,NaN,0.00,37.09,50,37.35,1,0.00,NaN
4,54.0,NaN,2001,3,48904,24.44,24.44,24.44,24.44,-1.0,0.05,24.41,50,24.64,8,0.00,NaN
5,55.0,NaN,89001,31,1500207,16.79,16.92,16.79,16.92,1.0,0.03,16.93,52,16.95,1,0.00,NaN
6,56.0,NaN,2438996,744,64241193,26.30,26.48,26.17,26.45,1.0,0.04,26.45,5,26.46,20,0.00,NaN
7,57.0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,51.60,1,51.85,20,0.00,NaN
8,58.0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,46.54,21,46.97,21,0.00,NaN
9,59.0,NaN,2001,3,83361,41.73,41.73,41.59,41.59,-1.0,0.51,41.80,1,42.20,1,0.00,NaN
10,61.0,NaN,4891073,782,98640896,20.04,20.33,20.00,20.26,-1.0,0.03,20.26,32,20.27,1,0.00,NaN
11,6203.0,NaN,49000,26,1911820,38.10,39.29,38.10,39.29,1.0,0.14,39.18,1,39.32,20,0.00,NaN
12,6204.0,NaN,4000,4,220250,54.70,55.30,54.70,55.30,NaN,0.00,55.10,20,55.30,100,0.00,NaN
13,6205.0,NaN,3632303,726,126045793,34.43,34.90,34.43,34.76,-1.0,0.05,34.75,6,34.76,7,0.00,NaN
14,6206.0,NaN,2532805,485,89786308,34.94,35.75,34.94,35.66,1.0,0.08,35.64,208,35.66,84,0.00,NaN
15,6207.0,NaN,1176578,209,30748778,26.10,26.30,25.99,26.20,1.0,0.04,26.19,1,26.20,32,0.00,NaN
16,6208.0,NaN,6095,10,297819,48.75,49.08,48.75,49.08,1.0,0.08,48.78,2,49.08,1,0.00,NaN
17,NaN,NaN,50000,2,378000,7.56,7.56,7.56,7.56,NaN,0.00,7.47,50,7.59,20,0.00,NaN
18,NaN,NaN,1930201,582,74175937,38.33,38.94,38.11,38.68,1.0,0.15,38.66,1,38.68,538,0.00,NaN
19,NaN,NaN,57642107,5709,729163283,12.68,12.70,12.56,12.61,-1.0,0.03,12.61,793,12.62,40,0.00,NaN
20,NaN,NaN,34163168,5954,1968711366,56.90,58.60,56.80,58.15,1.0,0.60,58.10,216,58.15,119,0.00,NaN
21,NaN,NaN,1278000,199,8184270,6.47,6.47,6.35,6.36,-1.0,0.04,6.36,318,6.39,150,0.00,NaN
22,NaN,NaN,296499,85,6117808,20.61,20.67,20.58,20.65,1.0,0.08,20.65,4,20.66,3,0.00,NaN
23,636.0,NaN,13298500,2068,307359041,22.84,23.35,22.81,23.25,1.0,0.13,23.24,40,23.25,70,0.00,NaN
24,NaN,NaN,164400,30,1315000,7.96,8.00,7.94,8.00,1.0,0.07,7.94,1,8.02,100,0.00,NaN
25,NaN,NaN,110110879,12337,2407775588,21.56,22.24,21.55,22.10,1.0,0.24,22.09,35,22.10,2390,0.00,NaN
26,NaN,NaN,520000,137,6729200,13.00,13.03,12.83,12.84,-1.0,0.09,12.84,131,12.85,1,0.00,NaN
27,639.0,NaN,3890090,676,47268641,12.13,12.23,12.10,12.18,-1.0,0.02,12.18,50,12.19,1,0.00,NaN
28,NaN,NaN,1136000,257,30323290,26.75,26.83,26.54,26.54,-1.0,0.36,26.51,10,26.54,88,0.00,NaN
29,NaN,NaN,778000,105,10923760,14.05,14.08,14.00,14.08,1.0,0.06,14.08,169,14.09,2,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13674,9110.0,NaN,3001,4,9923,3.35,3.35,3.25,3.32,1.0,0.02,3.25,4,3.32,3,0.00,NaN
13675,911608.0,NaN,51000,6,105740,1.94,2.10,1.94,2.10,-1.0,0.04,1.99,3,2.09,4,0.00,NaN
13676,911616.0,NaN,11000,3,13080,1.18,1.19,1.18,1.19,NaN,0.00,1.19,12,1.25,5,0.00,NaN
13677,911619.0,NaN,2000,1,1860,0.93,0.93,0.93,0.93,NaN,0.00,0.79,4,0.92,2,0.00,NaN
13678,911622.0,NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,5.90,2,6.50,3,0.00,NaN
13679,911868.0,NaN,1000,1,1350,1.35,1.35,1.35,1.35,1.0,0.02,1.29,20,1.35,4,0.00,NaN
13680,912000.0,NaN,10000,2,29500,2.95,2.95,2.95,2.95,NaN,0.00,2.95,2,3.04,3,0.00,NaN
13681,912398.0,NaN,3000,1,24930,8.31,8.31,8.31,8.31,-1.0,0.03,8.31,5,8.45,10,0.00,NaN
13682,9136.0,NaN,215000,69,1847040,8.68,8.68,8.56,8.58,-1.0,0.10,8.57,23,8.58,2,0.00,NaN
13683,9157.0,NaN,123001,25,158941,1.30,1.33,1.27,1.33,-1.0,0.05,1.28,7,1.32,13,0.00,NaN
13684,9188.0,NaN,32000,6,170810,5.34,5.34,5.27,5.27,-1.0,0.03,5.27,11,5.34,43,0.00,NaN
13685,9802.0,NaN,158136,118,11295500,71.20,72.10,70.90,71.90,1.0,0.30,71.40,10,71.90,2,12.35,NaN
13686,9902.0,NaN,106454,55,1094873,10.30,10.30,10.25,10.30,-1.0,0.05,10.25,45,10.30,4,0.00,NaN
13687,9904.0,NaN,5191362,2563,202342968,38.75,39.25,38.60,39.20,1.0,0.35,39.15,97,39.20,43,8.73,NaN
13688,9905.0,NaN,36508,27,924003,25.35,25.35,25.20,25.35,NaN,0.00,25.30,3,25.40,15,12.49,NaN
13693,9911.0,NaN,3055079,1920,123157669,39.10,41.50,38.80,40.50,1.0,1.35,40.20,23,40.50,18,13.68,NaN
13698,9919.0,NaN,211656,105,2582401,12.20,12.35,12.10,12.20,NaN,0.00,12.15,39,12.20,7,0.00,NaN
13700,9924.0,NaN,282827,178,10597101,37.75,37.75,37.30,37.45,-1.0,0.30,37.40,16,37.55,2,11.52,NaN
13703,9927.0,NaN,236017,143,9390521,39.90,39.90,39.70,39.85,-1.0,0.15,39.85,6,39.90,1,8.55,NaN
13704,9928.0,NaN,23191,11,120098,5.30,5.35,5.12,5.35,1.0,0.23,4.97,2,5.35,1,0.00,NaN
13708,9933.0,NaN,936111,628,42383559,45.55,45.55,45.10,45.30,-1.0,0.40,45.25,6,45.30,92,12.98,NaN
13709,9934.0,NaN,597225,406,11535610,19.40,19.50,19.25,19.50,NaN,0.00,19.45,24,19.50,518,10.00,NaN
13713,9939.0,NaN,613636,445,34508136,56.50,56.50,56.00,56.20,-1.0,0.30,56.20,30,56.30,1,12.92,NaN
13714,9940.0,NaN,398844,253,15192048,38.45,38.45,37.95,38.10,-1.0,0.35,38.05,19,38.10,9,8.74,NaN
13715,9941.0,NaN,470525,400,53252350,112.50,115.00,111.00,113.50,1.0,0.50,113.50,7,114.00,26,14.63,NaN
13716,9942.0,NaN,39300,35,3587719,91.00,91.40,91.00,91.40,1.0,0.40,91.40,1,91.50,3,14.33,NaN
13717,9943.0,NaN,64726,69,3487204,53.80,54.10,53.70,54.10,-1.0,0.10,54.00,1,54.10,8,12.41,NaN
13719,9945.0,NaN,3736138,1927,124164872,33.00,33.70,32.65,33.45,1.0,0.40,33.45,15,33.50,52,7.55,NaN
13720,9946.0,NaN,188743,83,2429334,12.80,13.00,12.80,13.00,-1.0,0.05,12.90,3,13.00,4,13.98,NaN
13721,9955.0,NaN,69012,49,1037730,14.80,15.15,14.80,15.00,1.0,0.20,14.95,7,15.00,1,0.00,NaN